local WavesService = {}
--[[
    This is where RNGs, opps, obstacles come into play. Anything that challenges player
    not just waves I guess, but I it cant be too smooth sailing.

    In NOTFM, there's literal enemies to fight. Enemies opposing each one of our six cards.
    In SAB, it's other players, whos trynna steal yo b. Also reward system is random.

    RNG waves,
    Spinwheel lottery,

    I dont want to go too complex, maybe just waves is fine? and events?
    linear. Say I want to play for about 2hrs
    2 * 60 * 60 = 7200 secs
    7200 each second is sets the rate to the square of the total seconds

    All the traders are wandering
    or
    The Nymphs wanders the forest
]]
return WavesService
